apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-service
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator-service
            image: yugani03it/aggregator-service:latest
            env:
            - name: DB_HOST
              value: "medi-track-cluster.cbbshrcivxlr.us-east-1.redshift.amazonaws.com:5439/dev"
            - name: DB_NAME
              value: "meditrack"
            - name: DB_USER
              value: "awsuser"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          restartPolicy: OnFailure
