apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
