apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record-service
    environment: blue  # Initially routes to the Blue environment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
