name: CI/CD Pipeline for yugani-cluster

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Patient Record Service
        run: |
          docker buildx build . --platform linux/amd64  -t yugani03it/patient-record-service:latest --push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure kubectl for yugani-cluster
        run: |
          aws eks update-kubeconfig --region ap-sount-1 --name yugani-cluster

      - name: Deploy Green Environment
        run: |
          kubectl apply -f k8s-artifacts/patient-record-deployment-green.yaml

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run Post-Deployment Tests
        run: |
          curl http://patient-record-service-green/health || exit 1

  switch:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Switch Traffic to Green Environment
        run: |
          kubectl patch service patient-record-service -p '{"spec":{"selector":{"app":"patient-record-service","environment":"green"}}}'
